#!/usr/bin/env node
// Renders the activity log — who did what to the world, newest first.
//
// The log is *derived*, never written. Every agent already records itself when it commits: an in-voice subject,
// a couple of lines of body, an `Agent:` trailer, and a link to the run that produced it. Having agents append to
// a shared log file instead would put every one of them on the same lines of the same file, which is the one
// merge conflict the commit step's rebase loop cannot resolve.
//
//   node scripts/activity.mjs                 # print to stdout
//   node scripts/activity.mjs --out log/activity.md
//   node scripts/activity.mjs --limit 200 --days 30

import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? fallback : process.argv[i + 1];
};

const LIMIT = Number(arg("limit", 150));
const DAYS = Number(arg("days", 30));
const OUT = arg("out", null);

const git = (...args) => execFileSync("git", args, { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });

const repo =
  process.env.GITHUB_REPOSITORY ||
  (git("remote", "get-url", "origin").match(/github\.com[:/](.+?)(?:\.git)?\s*$/)?.[1] ?? null);
const server = process.env.GITHUB_SERVER_URL || "https://github.com";
const base = repo ? `${server}/${repo}` : null;

const RS = "\x1e";
const US = "\x1f";

const raw = git(
  "log",
  `-${LIMIT}`,
  `--since=${DAYS} days ago`,
  "--no-merges",
  // This job's own commits are not activity; leaving them in would fill the log with itself.
  "--invert-grep",
  "--grep=^Render the activity log$",
  "--name-only",
  `--format=${RS}%H${US}%aI${US}%s${US}%b${US}`,
);

const commits = raw
  .split(RS)
  .slice(1)
  .map((chunk) => {
    const [hash, date, subject, body, files] = chunk.split(US);
    const agent = body.match(/^Agent:\s*(.+)$/m)?.[1]?.trim();
    const run = body.match(/^Run:\s*(\S+)$/m)?.[1];
    // Commits arrive from runners in UTC and from humans in local time; normalise or the day headings interleave.
    const at = new Date(date).toISOString();
    // Trailers are for machines. What's left is what the agent chose to say, clipped so the log stays scannable.
    let note = body
      .split("\n")
      .filter((l) => l.trim() && !/^(Agent|Run|Co-authored-by|Copilot-Session):/.test(l))
      .join(" ")
      .trim();
    if (note.length > 320) note = `${note.slice(0, 317).replace(/\s+\S*$/, "")}…`;
    return {
      hash,
      at,
      subject,
      note,
      run,
      agent: agent && agent !== "unknown" ? agent : run ? "an agent" : "manual",
      files: (files ?? "").split("\n").map((f) => f.trim()).filter(Boolean),
    };
  })
  .sort((a, b) => b.at.localeCompare(a.at));

const link = (text, href) => (href ? `[${text}](${href})` : text);
const short = (h) => h.slice(0, 7);

const out = [];
out.push("# Activity");
out.push("");
out.push(
  "Every change any agent has made to the world, newest first. Generated from the commit history by",
  "[`scripts/activity.mjs`](../scripts/activity.mjs) — **do not edit this file**, your edits will be overwritten.",
);
out.push("");
out.push(`Last ${DAYS} days. For the world's own account of events, read the [Chronicle](../codex/chronicle/README.md);`);
out.push("this is the machine's account of the agents that wrote it.");
out.push("");

let day = null;
for (const c of commits) {
  const d = c.at.slice(0, 10);
  if (d !== day) {
    day = d;
    out.push("", `## ${d}`, "");
  }

  const refs = [link(`\`${short(c.hash)}\``, base && `${base}/commit/${c.hash}`)];
  if (c.run) refs.push(link("run", c.run));

  out.push(`### ${c.subject}`);
  out.push(`**${c.agent}** · ${c.at.slice(11, 16)} · ${refs.join(" · ")}`);
  if (c.note) out.push("", c.note);
  if (c.files.length) {
    const shown = c.files.slice(0, 8).map((f) => link(`\`${f}\``, base && `${base}/blob/main/${f}`));
    if (c.files.length > 8) shown.push(`_and ${c.files.length - 8} more_`);
    out.push("", shown.join(" · "));
  }
  out.push("");
}

if (!commits.length) out.push("_Nothing in this window._", "");

const text = out.join("\n").replace(/\n{3,}/g, "\n\n");

if (OUT) {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, text);
  console.error(`Wrote ${OUT} — ${commits.length} commits.`);
} else {
  process.stdout.write(text);
}
