#!/usr/bin/env node
// Renders the party roster in codex/state.md from the hero sheets.
//
// The roster is derived data: every fact in it already lives in a hero's own sheet. Writing it by hand meant three
// agents (Dungeon Master, Adventurer, Recruiter) editing the same eight table rows of the same file in parallel,
// which is exactly the conflict the commit step's rebase loop cannot resolve — during the fast-forward it cost five
// runs their entire turn. Now each agent writes only its own hero's frontmatter, eight separate files, and this
// assembles them. Same information, no shared lines.
//
//   node scripts/party.mjs           # print the table
//   node scripts/party.mjs --write   # splice it into codex/state.md between the markers
//
// The sheet carries four optional fields beyond the usual frontmatter:
//
//   where:      short place name, plain text        ("The Drowned Kiln")
//   where_link: path from codex/, no leading slash  ("world/geography/sites/the-drowned-kiln.md")
//   doing:      one clause, present tense           ("Sixty feet down, wounded, no chain, the tide making")
//   quest:      path from codex/ to the quest file  ("quests/the-kiln-still-burns.md")
//
// Paths are relative to codex/ because state.md lives at codex/state.md, so they need no rewriting. A sheet missing
// a field degrades to an em dash rather than failing: a half-filled row still tells you the hero exists.

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const CHARACTERS = join(ROOT, "codex", "characters");
const STATE = join(ROOT, "codex", "state.md");
const WRITE = process.argv.includes("--write");

const BEGIN = "<!-- party:begin -->";
const END = "<!-- party:end -->";

// Deliberately not a YAML parser. The sheets are written by language models, and a dependency that throws on a
// stray colon would take the roster down for a quoting mistake. Unquote, and take everything after the first colon.
const frontmatter = (text) => {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return {};
  const fields = {};
  for (const line of m[1].split(/\r?\n/)) {
    const at = line.indexOf(":");
    if (at === -1 || line.startsWith("#")) continue;
    const value = line.slice(at + 1).trim();
    fields[line.slice(0, at).trim()] = value.replace(/^["'](.*)["']$/, "$1");
  }
  return fields;
};

const titleOf = (text, fallback) => (text.match(/^#\s+(.+)$/m)?.[1] ?? fallback).trim();

// Pipes would split a table cell in half, and the sheets are free text. Escape rather than reject.
const cell = (s) => (s ?? "").replace(/\|/g, "\\|").trim() || "—";
const link = (label, path) => (path ? `[${label}](${path})` : label);

const heroes = readdirSync(CHARACTERS, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(join(CHARACTERS, d.name, "sheet.md")))
  .map((d) => {
    const rel = `characters/${d.name}/sheet.md`;
    const text = readFileSync(join(CHARACTERS, d.name, "sheet.md"), "utf8");
    const f = frontmatter(text);
    return { dir: d.name, rel, name: titleOf(text, d.name), ...f };
  })
  // Recruitment order, so the table reads as the party's history and a new hero lands at the bottom rather than
  // shuffling everyone else's row. Sheets predating the `recruited:` field sort first, by directory name.
  .sort((a, b) => (a.recruited ?? "").localeCompare(b.recruited ?? "") || a.dir.localeCompare(b.dir));

const living = heroes.filter((h) => h.status !== "dead");
const fallen = heroes.filter((h) => h.status === "dead");

const rows = living.map((h) => {
  const where = h.where_link ? link(cell(h.where), h.where_link) : cell(h.where);
  const doing = h.quest ? `${cell(h.doing)} — ${link("quest", h.quest)}` : cell(h.doing);
  return `| ${link(h.name, h.rel)} | ${where} | ${doing} |`;
});

const out = [
  BEGIN,
  "",
  "<!-- Generated by scripts/party.mjs from the hero sheets. Edit the sheet's frontmatter, not this table. -->",
  "",
  "| Hero | Where | Doing what |",
  "| --- | --- | --- |",
  ...rows,
];

if (!living.length) out.push("| _nobody_ | — | The world is between heroes. |");
if (fallen.length) {
  out.push(
    "",
    `**Fallen.** ${fallen.map((h) => link(h.name, h.rel)).join(" · ")} — recorded in the ` +
      "[Chronicle](chronicle/README.md).",
  );
}
out.push("", END);

const table = out.join("\n");

if (!WRITE) {
  console.log(table);
  process.exit(0);
}

const state = readFileSync(STATE, "utf8");
const from = state.indexOf(BEGIN);
const to = state.indexOf(END);
if (from === -1 || to === -1) {
  console.error(`codex/state.md has no ${BEGIN} / ${END} markers — refusing to guess where the roster goes.`);
  process.exit(1);
}

const eol = state.includes("\r\n") ? "\r\n" : "\n";
const next = state.slice(0, from) + table.replace(/\n/g, eol) + state.slice(to + END.length);
if (next === state) {
  console.log("The roster is current.");
  process.exit(0);
}

writeFileSync(STATE, next);
console.log(`Rendered ${living.length} hero(es)${fallen.length ? `, ${fallen.length} fallen` : ""}.`);
